In [2]:
import nashpy as nash #for analysis
import requests #to get webpage html
import numpy as np
from bs4 import BeautifulSoup #to sort through html and get workable text

In [2]:
with open('dota items.txt', 'w') as textfile:
    textfile.write(str("Abyssal Blade\nAeon Disk\nAether Lens\nAghanim's Scepter\nArcane Boots\nArmlet of Mordiggian\nAssault Cuirass\nBattle Fury\nBlack King Bar\nBlade Mail\nBlink Dagger\nBloodstone\nBloodthorn\nBoots of Travel\nBracer\nButterfly\nCrimson Guard\nDaedalus\nDagon\nDesolator\nDiffusal Blade\nDivine Rapier\nDragon Lance\nDrum of Endurance\nEcho Sabre\nEthereal Blade\nEul's Scepter of Divinity\nEye of Skadi\nForce Staff\nGlimmer Cape\nGuardian Greaves\nHand of Midas\nHeart of Tarrasque\nHeaven's Halberd\nHelm of the Dominator\nHoly Locket\nHurricane Pike\nKaya and Sange\nLinken's Sphere\nLotus Orb\nManta Style\nMask of Madness\nMekansm\nMeteor Hammer\nMjollnir\nMonkey King Bar\nMoon Shard\nNecronomicon\nNullifier\nOctarine Core\nPhase Boots\nPipe of Insight\nPower Treads\nRadiance\nRefresher Orb\nRod of Atos\nSange and Yasha\nSatanic\nScythe of Vyse\nShadow Blade\nShiva's Guard\nSilver Edge\nSolar Crest\nSoul Ring\nSpirit Vessel\nTranquil Boots\nVeil of Discord\nVladmir's Offering\nYasha and Kaya"))
    
with open('dota items.txt', 'r') as textfile:
    data = textfile.read()
    
dotaitems = data.split("\n") #this gives a complete list of the items that we are interested in

In [3]:
slarkPage = requests.get("https://dota2.gamepedia.com/Slark")
soup = BeautifulSoup(slarkPage.text, 'html.parser')
rawtext = soup.get_text()

In [4]:
Slarkitems = []
for item in dotaitems:
    if item in rawtext:
        print("Yes, " + item + " is on the page")
        Slarkitems.append(item)

Yes, Abyssal Blade is on the page
Yes, Black King Bar is on the page
Yes, Butterfly is on the page
Yes, Drum of Endurance is on the page
Yes, Echo Sabre is on the page
Yes, Eye of Skadi is on the page
Yes, Force Staff is on the page
Yes, Hurricane Pike is on the page
Yes, Monkey King Bar is on the page
Yes, Moon Shard is on the page
Yes, Power Treads is on the page
Yes, Sange and Yasha is on the page
Yes, Shadow Blade is on the page
Yes, Silver Edge is on the page


In [5]:
Slarkitems.remove('Force Staff') #items used in the description of pounce, not useful for slark
Slarkitems.remove('Hurricane Pike') #items used in the description of pounce, not useful for slark

In [6]:
PAPage = requests.get("https://dota2.gamepedia.com/Phantom_Assassin")
soup = BeautifulSoup(PAPage.text, 'html.parser')
rawtext = soup.get_text()
PAitems = []
for item in dotaitems:
    if item in rawtext:
        print("Yes, " + item + " is on the page")
        PAitems.append(item)

Yes, Abyssal Blade is on the page
Yes, Assault Cuirass is on the page
Yes, Battle Fury is on the page
Yes, Black King Bar is on the page
Yes, Butterfly is on the page
Yes, Desolator is on the page
Yes, Eye of Skadi is on the page
Yes, Mask of Madness is on the page
Yes, Monkey King Bar is on the page
Yes, Nullifier is on the page
Yes, Power Treads is on the page
Yes, Sange and Yasha is on the page
Yes, Satanic is on the page


In [7]:
len(dotaitems) #still too many items to consider, look at reducing this based on the agility hero aspect

69

In [8]:
print(dotaitems)

['Abyssal Blade', 'Aeon Disk', 'Aether Lens', "Aghanim's Scepter", 'Arcane Boots', 'Armlet of Mordiggian', 'Assault Cuirass', 'Battle Fury', 'Black King Bar', 'Blade Mail', 'Blink Dagger', 'Bloodstone', 'Bloodthorn', 'Boots of Travel', 'Bracer', 'Butterfly', 'Crimson Guard', 'Daedalus', 'Dagon', 'Desolator', 'Diffusal Blade', 'Divine Rapier', 'Dragon Lance', 'Drum of Endurance', 'Echo Sabre', 'Ethereal Blade', "Eul's Scepter of Divinity", 'Eye of Skadi', 'Force Staff', 'Glimmer Cape', 'Guardian Greaves', 'Hand of Midas', 'Heart of Tarrasque', "Heaven's Halberd", 'Helm of the Dominator', 'Holy Locket', 'Hurricane Pike', 'Kaya and Sange', "Linken's Sphere", 'Lotus Orb', 'Manta Style', 'Mask of Madness', 'Mekansm', 'Meteor Hammer', 'Mjollnir', 'Monkey King Bar', 'Moon Shard', 'Necronomicon', 'Nullifier', 'Octarine Core', 'Phase Boots', 'Pipe of Insight', 'Power Treads', 'Radiance', 'Refresher Orb', 'Rod of Atos', 'Sange and Yasha', 'Satanic', 'Scythe of Vyse', 'Shadow Blade', "Shiva's Gua

In [9]:
undesirable_items = ['Aeon Disk', 'Aether Lens', "Aghanim's Scepter", 'Arcane Boots', 'Blade Mail', 'Bloodstone', 'Bloodthorn', 'Bracer', 'Crimson Guard', 'Dagon','Dragon Lance', "Eul's Scepter of Divinity", 'Force Staff', 'Glimmer Cape', 'Holy Locket', 'Hurricane Pike', 'Kaya and Sange', 'Mekansm', 'Meteor Hammer', 'Necronomicon', 'Octarine Core','Refresher Orb', 'Rod of Atos', 'Soul Ring', 'Spirit Vessel', 'Tranquil Boots','Veil of Discord' ]

for item in undesirable_items:
    if item in dotaitems:
        dotaitems.remove(item)
    
len(dotaitems) #42 items remain in the potential pool of items.

42

In [10]:
def baseitemvalues(hero, round):
    """Returns the base values for the payoff matrix"""
    itemvaluelist = []
    if hero in {"PA", "pa", "Phantom Assassin"}:
        x = PAitems
    elif hero in {"slark","Slark"}:
        x = Slarkitems
    else:
        x = "Hero not yet considered"
    
    for item in dotaitems:
        
        itemPage = requests.get("https://dota2.gamepedia.com/" + item)
        tempsoup = BeautifulSoup(itemPage.text, 'html.parser')
        rawtext2 = tempsoup.get_text()
        webpagewords = rawtext2.split()


        for word in webpagewords:
            if word.find('Cost') > -1:
                itemcost = int(word.strip("Cost")) #this is the cost of the item
                break
        if round == 1:        
            if itemcost < 2000:
                morepoints = 2 #gives the players more incentive to buy cheaper items earlier on, as it makes more sense
            else:
                morepoints = 0 
        elif round < 5:
            if 2000 < itemcost < 4500:
                morepoints = 2 #gives the players more incentive to buy cheaper items earlier on, as it makes more sense
            else:
                morepoints = 0 
        elif round > 4:
            morepoints = 0
        
        if item in x:
            itemvaluelist.append(2 + morepoints)
            
        else:
            itemvaluelist.append(0 + morepoints)
    
    print(itemvaluelist)
    


In [11]:
baseitemvalues("pa", 1) #manually adjusted in excel document based on opponents item choice

[2, 0, 2, 2, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 2, 0, 2, 2, 0, 4, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0]


In [16]:
baseitemvalues("Slark", 1) #manually adjusted in excel document as above

[2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 4, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 0, 4, 0, 2, 0, 0, 2, 0, 2, 0, 2, 0]


In [12]:
PAR1 = np.array([[2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,3,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,3,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,4,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,3,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0],  [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,2,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,0,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,3,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0], [2,0,2,2,2,0,0,2,0,3,0,0,2,0,0,2,0,0,0,0,2,0,0,0,3,0,2,0,2,4,0,4,0,2,2,0,0,0,0,0,2,0]])

In [14]:
SlarkR1 = np.array([[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,3,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,4,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3], [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]])

In [1]:
#game = nash.Game(SlarkR1, PAR1)
#list(game.support_enumeration())
#print('finished')""" 
#Support enumeration does not function well here, need to use vertex enumeration

"game = nash.Game(SlarkR1, PAR1)\nlist(game.support_enumeration())\nprint('finished')"

In [22]:
gameR1 = nash.Game(SlarkR1, PAR1)
list(gameR1.vertex_enumeration())

[(array([-3.46944695e-18, -3.46944695e-18, -3.46944695e-18, -3.46944695e-18,
         -3.46944695e-18, -3.46944695e-18, -3.46944695e-18, -3.46944695e-18,
         -3.46944695e-18, -3.46944695e-18, -3.46944695e-18, -3.46944695e-18,
         -3.46944695e-18, -3.46944695e-18, -3.46944695e-18, -3.46944695e-18,
         -3.46944695e-18, -3.46944695e-18, -3.46944695e-18, -3.46944695e-18,
         -3.46944695e-18, -3.46944695e-18, -3.46944695e-18, -3.46944695e-18,
         -3.46944695e-18, -3.46944695e-18, -3.46944695e-18, -3.46944695e-18,
         -3.46944695e-18, -3.46944695e-18, -3.46944695e-18,  1.00000000e+00,
         -3.46944695e-18, -3.46944695e-18, -3.46944695e-18, -3.46944695e-18,
         -3.46944695e-18, -3.46944695e-18, -3.46944695e-18, -3.46944695e-18,
         -3.46944695e-18, -3.46944695e-18]),
  array([-3.46944695e-18, -3.46944695e-18, -3.46944695e-18, -3.46944695e-18,
         -3.46944695e-18, -3.46944695e-18, -3.46944695e-18, -3.46944695e-18,
         -3.46944695e-18, -3.46

Our nash equilibria are [(Power Treads, Power Treads), (Power Treads, Phase Boots)], so the first items picked up are boots which is an expected outcome as mobility is key in the game.
Next we play the game again, looking at two scenarios (one with both players going Power Treads, the other with Power Treads and Phase Boots)
(Note all pairings refer to Slark, PA). We will also remove the boots selected and also all other pairs of boots (primarily to reduce the size of the problem, as gettings more than one pair of boots is not feasible).

In [24]:
baseitemvalues("pa", 2)

[2, 2, 2, 4, 4, 2, 2, 2, 0, 4, 2, 0, 0, 2, 0, 2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0, 4, 2, 2, 0, 2, 2, 0, 4, 2, 0, 2, 0, 0, 2, 0, 2]


In [25]:
baseitemvalues("Slark", 2)

[2, 2, 0, 2, 4, 2, 2, 2, 0, 2, 2, 0, 2, 4, 0, 2, 0, 2, 0, 2, 0, 0, 2, 0, 0, 0, 4, 4, 0, 0, 2, 2, 0, 4, 0, 0, 4, 0, 2, 2, 0, 2]


In [3]:
SlarkR2 = np.array([[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,5,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,5,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,4,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,5,4,4,4,4,4,4,4,4,4], [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2]])
PAR2A = np.array([[2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,6,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,5,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,4,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,3,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,5,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,0,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,5,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2]])
PAR2B = np.array([[2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,6,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,5,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,4,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,3,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,5,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,0,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,5,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,3,4,2,2,0,4,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2]])

In [4]:
gameR2A = nash.Game(SlarkR2, PAR2A)
list(gameR2A.vertex_enumeration())

[(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.])),
 (array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0.])),
 (array([-1.30104261e-17, -3.46944695e-17, -5.20417043e-17,  5.00000000e-01,
         -1.30104261e-17, -1.30104261e-17, -1.30104261e-17, -1.30104261e-17,
         -1.30104261e-17, -1.30104261e-17, -1.30104261e-17, -1.30104261e-17,
          5.00000000e-01, -1.30104261e-17, 

In [6]:
gameR2B = nash.Game(SlarkR2, PAR2B)
list(gameR2B.vertex_enumeration())

[(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.])),
 (array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0.])),
 (array([1.25767452e-16, 8.67361738e-18, 5.20417043e-17, 6.66666667e-01,
         7.80625564e-17, 6.50521303e-17, 7.37257477e-17, 7.37257477e-17,
         7.37257477e-17, 7.37257477e-17, 7.37257477e-17, 6.50521303e-17,
         3.33333333e-01, 7.80625564e-17, 7.80625564e-17

**Round 2 Game A results (Slark: Treads, PA: Treads)**

* Hand of midas - Hand of Midas
* Echo Sabre - Sange and Yasha
* Battlefury/Echo Sabre - Battlefury
* Battlefury - Battlefury

**Round 2 Game B results (Slark: Treads, PA: Phase Boots)**

* Hand of Midas - Hand of Midas
* Echo Sabre - Sange and Yasha
* 2/3 Battlefury/ Echo Sabre 1/3 - Battlefury
* Battlefury - Battlefury

In [12]:
SlarkR3A = np.array([[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [2,0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [4,4,4,4,4,4,4,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,5,4,4,4,4,4,4,4,4,4], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,4,4,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2]]) 
SlarkR3B = np.array([[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,3,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [3,3,3,3,3,5,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,5,3,3,3,3,3,3,3,3,3], [3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,4,4,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2]])
SlarkR3C = np.array([[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,3,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,4,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,4,4,4,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2]])
SlarkR3D = np.array([[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,5,4,4,4,4,4,4,4,4,4], [3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,4,4,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0]])
PAR3A = np.array([[2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,5,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,3,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,5,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,0,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,5,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2]])
PAR3B = np.array([[2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,5,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,4,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,3,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,0,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,5,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2]])
PAR3C = np.array([[2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,6,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,5,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,4,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,3,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,5,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,0,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,5,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2]])
PAR3D = np.array([[2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,5,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,3,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,5,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,0,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,5,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,5,2,0,2,0,0,2,0,2]])

In [13]:
#As the situation for buying any pair for boots remains the same after (i.e. each hero only wants to buy one pair of boots, so the payoff matrices are equivalent for each scenario), so we can just do 4 games instead of 8 and copy the results for the other one without any data loss.

gameR3A = nash.Game(SlarkR3A, PAR3A)
gameR3B = nash.Game(SlarkR3B, PAR3B)
gameR3C = nash.Game(SlarkR3C, PAR3C)
gameR3D = nash.Game(SlarkR3D, PAR3D)


In [14]:
list(gameR3A.vertex_enumeration())

[(array([4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 1.00000000e+00, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 0.])),
 (array([4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.336808

In [11]:
list(gameR3B.vertex_enumeration())

[(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
         0., 0.])),
 (array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.])),
 (array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
         0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [18]:
list(gameR3C.vertex_enumeration())

[(array([4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 1.00000000e+00, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18]),
  array([4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         1.00000000e+00, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18,

In [14]:
list(gameR3D.vertex_enumeration())

[(array([4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 1.00000000e+00, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18]),
  array([4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18, 4.33680869e-18, 4.33680869e-18, 4.33680869e-18,
         4.33680869e-18,

**Round 3 Game A results (Slark: Hand of Midas, PA: Hand of Midas)**

* Silver Edge - Sange and Yasha
* Silver Edge - Desolator

**Round 3 Game B results (Slark: Echo Sabre, PA: Sange and Yasha)**

* Silver Edge - Sange and Yasha
* Silver Edge - Desolator
* Sange and Yasha - Desolator

**Round 3 Game C results (Slark: Echo Sabre, PA: Battlefury)**

* Silver Edge - Desolator
* Sange of Yasha - Desolator

**Round 3 Game D results (Slark: Battlefury, PA: Battlefury)**

* Silver Edge - Sange and Yasha
* Silver Edge - Desolator
* Sange and Yasha - Desolator

In [30]:
SlarkR4A = np.array([[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [2,0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [4,4,4,4,4,4,4,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,4,4,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2]])
SlarkR4B = np.array([[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [2,0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [4,4,4,4,4,4,4,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,4,4,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2]])
SlarkR4C = np.array([[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [2,0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [4,4,4,4,4,4,4,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,4,4,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2]])
PAR4A = np.array([[2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,5,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,4,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,3,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,5,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,0,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,5,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,6,2,0,2,0,0,2,0,2]])
PAR4B = np.array([[2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,5,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,4,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,3,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,5,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,0,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,5,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,4,2,2,0,6,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2]])
PAR4C = np.array([[2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,5,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,4,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,3,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,5,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,0,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,5,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2], [2,2,2,7,2,2,0,5,2,0,0,2,0,2,2,0,2,0,0,2,0,2,0,4,2,2,2,0,2,0,2,0,0,2,0,2]])


In [31]:
gameR4A = nash.Game(SlarkR4A, PAR4A)
gameR4B = nash.Game(SlarkR4B, PAR4B)
gameR4C = nash.Game(SlarkR4C, PAR4C)

In [28]:
list(gameR4A.vertex_enumeration())

[(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 0.]))]

In [29]:
list(gameR4B.vertex_enumeration())

[(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.]))]

In [32]:
list(gameR4C.vertex_enumeration())

[(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.]),
  array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.]))]

**Round 4 Results**

At this point slark needs to pick up a key item because of PA, so for every scenario slark will get Monkey King Bar. PA will pick up either Sange and Yasha or Desolator depending on what item was purhcased in round 3. Apart from 4C, where PA has both items and will go for a Black King Bar so she can fight earlier. Item progression is shown on flowchart.